### ISSUE TITLE
improve error tracking for recurring errors

### ISSUE THREAD

**Issue by mattgi** [bentojs/api-log#1]
when ignoring subsequent errors we should actually update the existing error with information about the new error (e.g. time).

I think adding `count`, and `lastErrorAt` fields would be beneficial. This would allow a user to determine the error's duration (`createdAt` vs `lastErrorAt`) and how many times it occurred.

**Comment by Kodemon** [comment]
Added `count` which increments on reoccurring errors. You can check durration using `createdAt` and `updatedAt` values.
